name: Rick Seedman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86791
title: Rick Seedman - Personal Trainer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#464646'
    - '#ffffff'
    - '#000000'
    - '#bfbfbf'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
